// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/update.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	slog "log/slog"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/serg1732/practicum-yandex-metrics/internal/model"
)

// MockUpdateStorage is a mock of UpdateStorage interface.
type MockUpdateStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateStorageMockRecorder
}

// MockUpdateStorageMockRecorder is the mock recorder for MockUpdateStorage.
type MockUpdateStorageMockRecorder struct {
	mock *MockUpdateStorage
}

// NewMockUpdateStorage creates a new mock instance.
func NewMockUpdateStorage(ctrl *gomock.Controller) *MockUpdateStorage {
	mock := &MockUpdateStorage{ctrl: ctrl}
	mock.recorder = &MockUpdateStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateStorage) EXPECT() *MockUpdateStorageMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateStorage) Update(ctx context.Context, log *slog.Logger, Data *models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, log, Data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUpdateStorageMockRecorder) Update(ctx, log, Data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateStorage)(nil).Update), ctx, log, Data)
}

// Updates mocks base method.
func (m *MockUpdateStorage) Updates(ctx context.Context, log *slog.Logger, Data []*models.Metrics) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Updates", ctx, log, Data)
	ret0, _ := ret[0].(error)
	return ret0
}

// Updates indicates an expected call of Updates.
func (mr *MockUpdateStorageMockRecorder) Updates(ctx, log, Data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Updates", reflect.TypeOf((*MockUpdateStorage)(nil).Updates), ctx, log, Data)
}

// MockAuditor is a mock of Auditor interface.
type MockAuditor struct {
	ctrl     *gomock.Controller
	recorder *MockAuditorMockRecorder
}

// MockAuditorMockRecorder is the mock recorder for MockAuditor.
type MockAuditorMockRecorder struct {
	mock *MockAuditor
}

// NewMockAuditor creates a new mock instance.
func NewMockAuditor(ctrl *gomock.Controller) *MockAuditor {
	mock := &MockAuditor{ctrl: ctrl}
	mock.recorder = &MockAuditorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAuditor) EXPECT() *MockAuditorMockRecorder {
	return m.recorder
}

// BroadCast mocks base method.
func (m *MockAuditor) BroadCast(data *models.AuditEvent) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "BroadCast", data)
}

// BroadCast indicates an expected call of BroadCast.
func (mr *MockAuditorMockRecorder) BroadCast(data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "BroadCast", reflect.TypeOf((*MockAuditor)(nil).BroadCast), data)
}
