// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/read.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/serg1732/practicum-yandex-metrics/internal/model"
)

// MockReadStorage is a mock of ReadStorage interface.
type MockReadStorage struct {
	ctrl     *gomock.Controller
	recorder *MockReadStorageMockRecorder
}

// MockReadStorageMockRecorder is the mock recorder for MockReadStorage.
type MockReadStorageMockRecorder struct {
	mock *MockReadStorage
}

// NewMockReadStorage creates a new mock instance.
func NewMockReadStorage(ctrl *gomock.Controller) *MockReadStorage {
	mock := &MockReadStorage{ctrl: ctrl}
	mock.recorder = &MockReadStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockReadStorage) EXPECT() *MockReadStorageMockRecorder {
	return m.recorder
}

// GetAllCounters mocks base method.
func (m *MockReadStorage) GetAllCounters(ctx context.Context) (map[string]*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCounters", ctx)
	ret0, _ := ret[0].(map[string]*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllCounters indicates an expected call of GetAllCounters.
func (mr *MockReadStorageMockRecorder) GetAllCounters(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCounters", reflect.TypeOf((*MockReadStorage)(nil).GetAllCounters), ctx)
}

// GetAllGauges mocks base method.
func (m *MockReadStorage) GetAllGauges(ctx context.Context) (map[string]*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGauges", ctx)
	ret0, _ := ret[0].(map[string]*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllGauges indicates an expected call of GetAllGauges.
func (mr *MockReadStorageMockRecorder) GetAllGauges(ctx interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGauges", reflect.TypeOf((*MockReadStorage)(nil).GetAllGauges), ctx)
}

// GetCounter mocks base method.
func (m *MockReadStorage) GetCounter(ctx context.Context, name string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", ctx, name)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockReadStorageMockRecorder) GetCounter(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockReadStorage)(nil).GetCounter), ctx, name)
}

// GetGauge mocks base method.
func (m *MockReadStorage) GetGauge(ctx context.Context, name string) (*models.Metrics, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", ctx, name)
	ret0, _ := ret[0].(*models.Metrics)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockReadStorageMockRecorder) GetGauge(ctx, name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockReadStorage)(nil).GetGauge), ctx, name)
}
