// Code generated by MockGen. DO NOT EDIT.
// Source: internal/handler/update.go

// Package mocks is a generated GoMock package.
package mocks

import (
	slog "log/slog"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	models "github.com/serg1732/practicum-yandex-metrics/internal/model"
)

// MockUpdateStorage is a mock of UpdateStorage interface.
type MockUpdateStorage struct {
	ctrl     *gomock.Controller
	recorder *MockUpdateStorageMockRecorder
}

// MockUpdateStorageMockRecorder is the mock recorder for MockUpdateStorage.
type MockUpdateStorageMockRecorder struct {
	mock *MockUpdateStorage
}

// NewMockUpdateStorage creates a new mock instance.
func NewMockUpdateStorage(ctrl *gomock.Controller) *MockUpdateStorage {
	mock := &MockUpdateStorage{ctrl: ctrl}
	mock.recorder = &MockUpdateStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUpdateStorage) EXPECT() *MockUpdateStorageMockRecorder {
	return m.recorder
}

// Update mocks base method.
func (m *MockUpdateStorage) Update(log *slog.Logger, name string, Data *models.Metrics) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Update", log, name, Data)
}

// Update indicates an expected call of Update.
func (mr *MockUpdateStorageMockRecorder) Update(log, name, Data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUpdateStorage)(nil).Update), log, name, Data)
}
