// Code generated by MockGen. DO NOT EDIT.
// Source: internal/repository/metric_storage.go

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockMemStorage is a mock of MemStorage interface.
type MockMemStorage struct {
	ctrl     *gomock.Controller
	recorder *MockMemStorageMockRecorder
}

// MockMemStorageMockRecorder is the mock recorder for MockMemStorage.
type MockMemStorageMockRecorder struct {
	mock *MockMemStorage
}

// NewMockMemStorage creates a new mock instance.
func NewMockMemStorage(ctrl *gomock.Controller) *MockMemStorage {
	mock := &MockMemStorage{ctrl: ctrl}
	mock.recorder = &MockMemStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMemStorage) EXPECT() *MockMemStorageMockRecorder {
	return m.recorder
}

// GetAllCounters mocks base method.
func (m *MockMemStorage) GetAllCounters() map[string]*int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllCounters")
	ret0, _ := ret[0].(map[string]*int64)
	return ret0
}

// GetAllCounters indicates an expected call of GetAllCounters.
func (mr *MockMemStorageMockRecorder) GetAllCounters() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllCounters", reflect.TypeOf((*MockMemStorage)(nil).GetAllCounters))
}

// GetAllGauges mocks base method.
func (m *MockMemStorage) GetAllGauges() map[string]*float64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllGauges")
	ret0, _ := ret[0].(map[string]*float64)
	return ret0
}

// GetAllGauges indicates an expected call of GetAllGauges.
func (mr *MockMemStorageMockRecorder) GetAllGauges() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllGauges", reflect.TypeOf((*MockMemStorage)(nil).GetAllGauges))
}

// GetCounter mocks base method.
func (m *MockMemStorage) GetCounter(name string) (*int64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCounter", name)
	ret0, _ := ret[0].(*int64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetCounter indicates an expected call of GetCounter.
func (mr *MockMemStorageMockRecorder) GetCounter(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCounter", reflect.TypeOf((*MockMemStorage)(nil).GetCounter), name)
}

// GetGauge mocks base method.
func (m *MockMemStorage) GetGauge(name string) (*float64, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGauge", name)
	ret0, _ := ret[0].(*float64)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// GetGauge indicates an expected call of GetGauge.
func (mr *MockMemStorageMockRecorder) GetGauge(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGauge", reflect.TypeOf((*MockMemStorage)(nil).GetGauge), name)
}

// UpdateCounter mocks base method.
func (m *MockMemStorage) UpdateCounter(name string, Data *int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateCounter", name, Data)
}

// UpdateCounter indicates an expected call of UpdateCounter.
func (mr *MockMemStorageMockRecorder) UpdateCounter(name, Data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCounter", reflect.TypeOf((*MockMemStorage)(nil).UpdateCounter), name, Data)
}

// UpdateGauge mocks base method.
func (m *MockMemStorage) UpdateGauge(name string, Data *float64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "UpdateGauge", name, Data)
}

// UpdateGauge indicates an expected call of UpdateGauge.
func (mr *MockMemStorageMockRecorder) UpdateGauge(name, Data interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateGauge", reflect.TypeOf((*MockMemStorage)(nil).UpdateGauge), name, Data)
}
