package main

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"log"
	"os"
	"path/filepath"
	"strings"
	"text/template"
	"unicode"

	"golang.org/x/tools/imports"
)

const (
	marker            = "generate:reset"
	generatedFileName = "reset.gen.go"
)

type TemplateData struct {
	Package string
	Structs []StructTemplate
}

type StructTemplate struct {
	Name     string
	Receiver string
	Fields   []string
}

const fileTemplate = `
// Code generated by cmd/reset; DO NOT EDIT.

package {{ .Package }}

{{ range .Structs }}
func ({{ .Receiver }} *{{ .Name }}) Reset() {
	if {{ .Receiver }} == nil {
		return
	}

{{- range .Fields }}
	{{ . }}
{{- end }}
}
{{ end }}
`

func main() {
	root := "."

	err := filepath.WalkDir(root, func(path string, d os.DirEntry, err error) error {
		if err != nil {
			return err
		}

		if !d.IsDir() {
			return nil
		}

		base := filepath.Base(path)
		switch base {
		case ".git", "vendor":
			return filepath.SkipDir
		}

		if strings.Contains(path, "cmd/reset") {
			return filepath.SkipDir
		}
		return processDir(path)
	})

	if err != nil {
		log.Fatal(err)
	}
}

func processDir(dir string) error {
	fset := token.NewFileSet()

	entries, err := os.ReadDir(dir)
	if err != nil {
		return err
	}

	files := make(map[string]*ast.File)

	var pkgName string
	for _, entry := range entries {
		if entry.IsDir() {
			continue
		}

		name := entry.Name()
		if !strings.HasSuffix(name, ".go") {
			continue
		}

		if strings.HasSuffix(name, "_test.go") {
			continue
		}

		if name == generatedFileName {
			continue
		}

		fullPath := filepath.Join(dir, name)

		file, errParseFile := parser.ParseFile(
			fset,
			fullPath,
			nil,
			parser.ParseComments,
		)
		if errParseFile != nil {
			return err
		}

		files[fullPath] = file
		pkgName = file.Name.Name
	}

	if len(files) == 0 {
		return nil
	}

	data := TemplateData{
		Package: pkgName,
	}

	for _, file := range files {
		for _, decl := range file.Decls {
			genDecl, ok := decl.(*ast.GenDecl)
			if !ok || genDecl.Tok != token.TYPE {
				continue
			}

			for _, spec := range genDecl.Specs {
				typeSpec, isTypeSpec := spec.(*ast.TypeSpec)
				if !isTypeSpec {
					continue
				}

				structType, isStruct := typeSpec.Type.(*ast.StructType)
				if !isStruct {
					continue
				}

				if !hasMarker(genDecl.Doc) && !hasMarker(typeSpec.Doc) {
					continue
				}

				st := StructTemplate{
					Name:     typeSpec.Name.Name,
					Receiver: receiverName(typeSpec.Name.Name),
				}

				for _, field := range structType.Fields.List {
					names := fieldNames(field)

					for _, fieldName := range names {
						fieldExpr := st.Receiver + "." + fieldName

						st.Fields = append(
							st.Fields,
							buildFieldReset(
								fset,
								fieldExpr,
								field.Type,
							),
						)
					}
				}

				data.Structs = append(data.Structs, st)
			}
		}
	}

	if len(data.Structs) == 0 {
		return nil
	}
	return writeFile(dir, data)
}

func writeFile(dir string, data TemplateData) error {
	tmpl := template.Must(template.New("reset").Parse(fileTemplate))

	var buf bytes.Buffer

	if err := tmpl.Execute(&buf, data); err != nil {
		return err
	}

	src, err := format.Source(buf.Bytes())
	if err != nil {
		return fmt.Errorf("ошибка при форматировании fmt: %w\n%s", err, buf.String())
	}
	generatedFilePath := filepath.Join(dir, generatedFileName)
	result, errImports := imports.Process(generatedFileName, src, &imports.Options{
		Comments:   true,
		FormatOnly: false,
	})
	if errImports != nil {
		return errImports
	}
	errCreateFile := os.WriteFile(
		generatedFilePath,
		result,
		0644,
	)
	return errCreateFile
}

func buildFieldReset(fileSet *token.FileSet, expr string, typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.ArrayType:
		if t.Len == nil {
			return fmt.Sprintf("%s = %s[:0]", expr, expr)
		}

		return fmt.Sprintf("%s = %s", expr, zeroValue(fileSet, typ))

	case *ast.MapType:
		return fmt.Sprintf("clear(%s)", expr)

	case *ast.StarExpr:
		return fmt.Sprintf(
			`
						if resetter, ok := any(%[1]s).(interface{Reset()}); ok && %[1]s != nil {
							resetter.Reset()
						} else {
							*%[1]s = %[2]s
						}`, expr, zeroValue(fileSet, t.X))
	case *ast.StructType, *ast.Ident, *ast.SelectorExpr:
		return fmt.Sprintf(`%[1]s = %[2]s`, expr, zeroValue(fileSet, typ))

	default:
		return fmt.Sprintf("%s = %s", expr, zeroValue(fileSet, typ))
	}
}

func zeroValue(fset *token.FileSet, typ ast.Expr) string {
	switch t := typ.(type) {
	case *ast.Ident:
		switch t.Name {
		case "string":
			return `""`
		case "bool":
			return "false"
		case "int", "int8", "int16", "int32", "int64",
			"uint", "uint8", "uint16", "uint32", "uint64", "uintptr",
			"float32", "float64",
			"complex64", "complex128",
			"byte", "rune":
			return "0"
		case "error":
			return "nil"
		}

	case *ast.ChanType, *ast.FuncType, *ast.InterfaceType, *ast.MapType:
		return "nil"

	case *ast.ArrayType:
		return "*new(" + typeString(fset, typ) + ")"

	case *ast.StarExpr:
		return "nil"
	}

	return "*new(" + typeString(fset, typ) + ")"
}

func hasMarker(group *ast.CommentGroup) bool {
	if group == nil {
		return false
	}

	for _, comment := range group.List {
		if strings.Contains(comment.Text, marker) {
			return true
		}
	}
	return false
}

func fieldNames(field *ast.Field) []string {
	if len(field.Names) > 0 {
		result := make([]string, 0, len(field.Names))

		for _, name := range field.Names {
			if name.Name != "_" {
				result = append(result, name.Name)
			}
		}

		return result
	}

	name := embeddedFieldName(field.Type)
	if name == "" || name == "_" {
		return nil
	}
	return []string{name}
}

func embeddedFieldName(expr ast.Expr) string {
	switch t := expr.(type) {

	case *ast.Ident:
		return t.Name

	case *ast.StarExpr:
		return embeddedFieldName(t.X)

	case *ast.SelectorExpr:
		return t.Sel.Name

	default:
		return ""
	}
}

func typeString(fileSet *token.FileSet, expr ast.Expr) string {
	var buf bytes.Buffer
	_ = printer.Fprint(&buf, fileSet, expr)
	return buf.String()
}

func receiverName(typeName string) string {
	for _, r := range typeName {
		return strings.ToLower(string(unicode.ToLower(r)))
	}
	return "r"
}
